version: 2.0.{build}
skip_non_tags: true
image: Visual Studio 2019
configuration: Release
platform: 
- x64
- x86

for:
-
    matrix:
        only:
            - platform: x64
    install:
    - pwsh: .\scripts\prepare_x64.ps1

    build_script:
    - pwsh: mkdir build_x64
    - pwsh: cd .\build_x64
    - pwsh: cmake -G "Visual Studio 16 2019" -A x64  -DCMAKE_CONFIGURATION_TYPES:STRING="Release" -DCMAKE_INSTALL_PREFIX:PATH="C:\projects\mocliamusic\out\install\x64-Release" -DVCPKG_TARGET_TRIPLET=x64-windows-static  -DCMAKE_TOOLCHAIN_FILE="C:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake" "C:\projects\mocliamusic"
    - pwsh: cmake --build . --config "Release" --target "MocliaMusic"

-
    matrix:
        only:
            - platform: x86
    install:
    - pwsh: git clone https://github.com/microsoft/vcpkg.git C:\tools\vcpkg
    - pwsh: cd C:\tools
    - pwsh: git clone https://github.com/cyanray/mirai-cpp-vcpkg-port.git
    - pwsh: cd mirai-cpp-vcpkg-port
    - pwsh: copy -r C:\tools\mirai-cpp-vcpkg-port\mirai-cpp\ C:\tools\vcpkg\ports\mirai-cpp\
    - pwsh: cd C:\tools\vcpkg
    - pwsh: .\bootstrap-vcpkg.bat
    - pwsh: .\vcpkg integrate install
    - pwsh: .\vcpkg install cpr:x86-windows-static rapidjson:x86-windows-static fmt:x86-windows-static sqlitecpp:x86-windows-static sqlite3:x86-windows-static mirai-cpp:x86-windows-static
    
    build_script:
    - pwsh: mkdir build_x86
    - pwsh: cd .\build_x86
    - pwsh: cmake -G "Visual Studio 16 2019" -A x86  -DCMAKE_CONFIGURATION_TYPES:STRING="Release" -DCMAKE_INSTALL_PREFIX:PATH="C:\projects\mocliamusic\out\install\x86-Release" -DVCPKG_TARGET_TRIPLET=x86-windows-static  -DCMAKE_TOOLCHAIN_FILE="C:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake" "C:\projects\mocliamusic"
    - pwsh: cmake --build .. --config "Release" --target "MocliaMusic"