version: 2.0.{build}
skip_non_tags: true
image: Visual Studio 2019
configuration: Release
platform: 
- x64
- x86

for:
-
    matrix:
        only:
            - platform: x64
    install:
    - pwsh: .\scripts\prepare_win64.ps1

    build_script:
    - pwsh: .\scripts\build_win64.ps1

    artifacts:
    - path: .\build_x64\Release\MocliaMusic.exe
      name: MocliaMusic-Windows64.exe

-
    matrix:
        only:
            - platform: x86
    install:
     - pwsh: .\scripts\prepare_win86.ps1
    
    build_script:
    - pwsh: .\scripts\build_win86.ps1

    artifacts:
    - path: .\build_x86\Release\MocliaMusic.exe
      name: MocliaMusic-Windows86.exe